# Generated by Django 5.2.15 on 2026-06-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneLookupCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_phone', models.CharField(db_index=True, max_length=16, unique=True)),
                ('display_phone', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=32)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('result_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('raw_response', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['normalized_phone', '-updated_at'], name='lookups_pho_normali_95c895_idx'), models.Index(fields=['result_count', '-updated_at'], name='lookups_pho_result__20eee5_idx')],
            },
        ),
    ]
