# Generated by Django 5.2.15 on 2026-06-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistLookupCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_phone', models.CharField(db_index=True, max_length=16, unique=True)),
                ('phone_digits', models.CharField(db_index=True, max_length=10, unique=True)),
                ('display_phone', models.CharField(max_length=20)),
                ('summary_status', models.CharField(blank=True, db_index=True, max_length=255)),
                ('risk_category', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status_array', models.JSONField(blank=True, default=list)),
                ('is_bad_number', models.BooleanField(db_index=True, default=False)),
                ('raw_response', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['normalized_phone', '-updated_at'], name='lookups_bla_normali_0e294d_idx'), models.Index(fields=['risk_category', '-updated_at'], name='lookups_bla_risk_ca_f9dd27_idx'), models.Index(fields=['is_bad_number', '-updated_at'], name='lookups_bla_is_bad__e5e959_idx')],
            },
        ),
    ]
