# Generated by Django 5.2.15 on 2026-06-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0002_blacklistlookupcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneLookupAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('normalized_phone', models.CharField(db_index=True, max_length=16)),
                ('fetched_from_dbcache', models.BooleanField(db_index=True, default=False)),
                ('fetched_from_bla_cache', models.BooleanField(db_index=True, default=False)),
                ('public_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['normalized_phone', '-timestamp'], name='lookups_pho_normali_be8e92_idx'), models.Index(fields=['public_ip', '-timestamp'], name='lookups_pho_public__cfd1ca_idx')],
            },
        ),
    ]
