# Generated by Django 5.2.15 on 2026-06-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0003_phonelookupaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistlookupcache',
            name='bla_code',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blacklistlookupcache',
            name='tcpa_status',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
