# Generated by Django 5.2.15 on 2026-06-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0004_blacklistlookupcache_bla_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameAddrLookupCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_normalized', models.CharField(db_index=True, max_length=80)),
                ('last_name_normalized', models.CharField(db_index=True, max_length=160)),
                ('location_normalized', models.CharField(db_index=True, max_length=255)),
                ('zipcode', models.CharField(blank=True, db_index=True, max_length=10)),
                ('full_name', models.CharField(max_length=255)),
                ('address_or_zip', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=32)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('result_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('raw_response', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['first_name_normalized', 'last_name_normalized', 'location_normalized'], name='nameaddr_cache_key_idx'), models.Index(fields=['zipcode', '-updated_at'], name='nameaddr_zip_updated_idx'), models.Index(fields=['result_count', '-updated_at'], name='nameaddr_count_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('first_name_normalized', 'last_name_normalized', 'location_normalized'), name='unique_name_address_lookup_cache_key')],
            },
        ),
    ]
