# Generated by Django 5.2.15 on 2026-06-18 16:34

from django.db import migrations, models


def split_address_or_zip(apps, schema_editor):
    NameAddrLookupCache = apps.get_model('lookups', 'NameAddrLookupCache')

    for cache in NameAddrLookupCache.objects.all().iterator():
        if cache.zipcode:
            cache.address = ''
        else:
            cache.address = cache.address_or_zip
        cache.save(update_fields=['address'])


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0005_nameaddrlookupcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameaddrlookupcache',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.RunPython(split_address_or_zip, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='nameaddrlookupcache',
            name='address_or_zip',
        ),
    ]
