# Generated by Django 5.2.15 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0006_remove_nameaddrlookupcache_address_or_zip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonelookupcache',
            name='provider',
            field=models.CharField(
                choices=[('primary', 'Primary'), ('secondary', 'Secondary')],
                db_index=True,
                default='primary',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='phonelookupcache',
            name='secondary_attempted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='nameaddrlookupcache',
            name='provider',
            field=models.CharField(
                choices=[('primary', 'Primary'), ('secondary', 'Secondary')],
                db_index=True,
                default='primary',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='nameaddrlookupcache',
            name='secondary_attempted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
