# Generated by Django 5.2.15 on 2026-08-14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0007_nameaddrlookupcache_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryRelayConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('phone_endpoint', models.URLField(max_length=500)),
                ('name_endpoint', models.URLField(max_length=500)),
                (
                    'api_token',
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(32)],
                    ),
                ),
                (
                    'timeout_seconds',
                    models.PositiveSmallIntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'secondary relay configuration',
                'verbose_name_plural': 'secondary relay configuration',
            },
        ),
    ]
