# Generated by Django 5.2.15 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0008_secondaryrelayconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupIPAccessDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('allowed', models.BooleanField(db_index=True, default=False)),
                ('provider', models.CharField(default='ipinfo-lite', max_length=32)),
                ('checked_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [
                    models.Index(fields=['allowed', 'expires_at'], name='lookups_loo_allowed_7a2790_idx'),
                    models.Index(fields=['country_code', '-checked_at'], name='lookups_loo_country_4a2e19_idx'),
                ],
            },
        ),
    ]
