# Generated by Django 5.2.15 on 2026-08-14

from django.db import migrations, models


def backfill_phone_audit_success(apps, schema_editor):
    phone_audit = apps.get_model('lookups', 'PhoneLookupAudit')
    phone_cache = apps.get_model('lookups', 'PhoneLookupCache')
    successful_numbers = phone_cache.objects.filter(result_count__gt=0).values('normalized_phone')
    phone_audit.objects.filter(normalized_phone__in=successful_numbers).update(successful_result=True)


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0009_lookupipaccessdecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonelookupaudit',
            name='response_time_ms',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='phonelookupaudit',
            name='source',
            field=models.CharField(
                choices=[('primary', 'Primary'), ('secondary', 'Secondary')],
                db_index=True,
                default='primary',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='phonelookupaudit',
            name='successful_result',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(backfill_phone_audit_success, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='phonelookupaudit',
            index=models.Index(fields=['source', '-timestamp'], name='lookups_pho_source_794eae_idx'),
        ),
        migrations.CreateModel(
            name='NameLookupAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('full_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('fetched_from_dbcache', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], db_index=True, default='primary', max_length=16)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('successful_result', models.BooleanField(db_index=True, default=False)),
                ('public_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(fields=['source', '-timestamp'], name='lookups_nam_source_40c3a8_idx'),
                    models.Index(fields=['public_ip', '-timestamp'], name='lookups_nam_public__a987a3_idx'),
                ],
            },
        ),
    ]
