# Generated by Django 5.2.15 on 2026-06-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('experience', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Difficult', 'Difficult')], max_length=24)),
                ('areas', models.JSONField(blank=True, default=list)),
                ('feature', models.CharField(blank=True, max_length=160)),
                ('device', models.CharField(blank=True, max_length=40)),
                ('details', models.TextField()),
                ('suggestion', models.TextField(blank=True)),
                ('page_url', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('public_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='accounts_fe_is_read_01fbdd_idx'), models.Index(fields=['public_ip', '-created_at'], name='accounts_fe_public__5234cf_idx')],
            },
        ),
    ]
