"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path):
    if not path.exists():
        return

    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_env_file(BASE_DIR / '.env')


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


def env_int(name, default, minimum=None, maximum=None):
    try:
        value = int(os.environ.get(name, str(default)))
    except ValueError as exc:
        raise ImproperlyConfigured(f'{name} must be an integer.') from exc
    if minimum is not None and value < minimum:
        raise ImproperlyConfigured(f'{name} must be at least {minimum}.')
    if maximum is not None and value > maximum:
        raise ImproperlyConfigured(f'{name} must be at most {maximum}.')
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-%-$q&wd@uiw-q!agj)b&m+yv&&u9m(1i#lxgp1#e3hlg**l0n5',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)
CALLLOOM_ENABLED = env_bool('CALLLOOM_ENABLED', True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')

if not DEBUG:
    if SECRET_KEY.startswith('django-insecure-'):
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set to a strong secret in production.')
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS must be set in production.')
    required_production_env = [
        'IPINFO_API_TOKEN',
        'TCPA_BLACKLIST_API_KEY',
        'TURNSTILE_ALLOWED_HOSTNAMES',
        'TURNSTILE_SECRET_KEY',
    ]
    if CALLLOOM_ENABLED:
        required_production_env.append('CALLLOOM_API_KEY')
    missing_env = [name for name in required_production_env if not os.environ.get(name)]
    if missing_env:
        raise ImproperlyConfigured(f'Missing required production environment variables: {", ".join(missing_env)}')
    placeholder_env = [
        name for name in required_production_env if os.environ.get(name, '').startswith('replace-with-')
    ]
    if placeholder_env:
        raise ImproperlyConfigured(
            f'Replace placeholder production environment variables: {", ".join(placeholder_env)}'
        )
    if os.environ.get('TURNSTILE_SECRET_KEY', '').startswith('1x000000'):
        raise ImproperlyConfigured('TURNSTILE_SECRET_KEY must be a real Cloudflare Turnstile secret in production.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'accounts',
    'lookups',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('DJANGO_DATABASE_ENGINE') == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'peoplegraph'),
            'USER': os.environ.get('POSTGRES_USER', 'admin'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'peoplegraph43211234'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': int(os.environ.get('POSTGRES_CONN_MAX_AGE', '60')),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.environ.get('DJANGO_STATIC_URL', 'django-static/')
STATIC_ROOT = os.environ.get('DJANGO_STATIC_ROOT', BASE_DIR / 'staticfiles')
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = env_list(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000,http://localhost:3001,http://127.0.0.1:3001',
)
CORS_ALLOW_CREDENTIALS = False

LOOKUP_ALLOWED_ORIGINS = set(
    env_list('LOOKUP_ALLOWED_ORIGINS', ','.join(CORS_ALLOWED_ORIGINS))
)
LOOKUP_REQUIRE_TRUSTED_ORIGIN = env_bool('LOOKUP_REQUIRE_TRUSTED_ORIGIN', not DEBUG)
FEEDBACK_REQUIRE_TRUSTED_ORIGIN = env_bool('FEEDBACK_REQUIRE_TRUSTED_ORIGIN', not DEBUG)
TURNSTILE_EXPECTED_ACTION = os.environ.get('TURNSTILE_EXPECTED_ACTION', 'peoplegraph_lookup').strip()
TURNSTILE_ALLOWED_HOSTNAMES = set(env_list('TURNSTILE_ALLOWED_HOSTNAMES'))

LOOKUP_REGION_ENFORCEMENT_ENABLED = env_bool('LOOKUP_REGION_ENFORCEMENT_ENABLED', not DEBUG)
LOOKUP_ALLOW_PRIVATE_IPS_IN_DEBUG = env_bool('LOOKUP_ALLOW_PRIVATE_IPS_IN_DEBUG', True)
LOOKUP_ALLOWED_COUNTRY_CODE = os.environ.get('LOOKUP_ALLOWED_COUNTRY_CODE', 'PK').strip().upper()
if len(LOOKUP_ALLOWED_COUNTRY_CODE) != 2:
    raise ImproperlyConfigured('LOOKUP_ALLOWED_COUNTRY_CODE must be a two-letter country code.')
LOOKUP_REGION_RESTRICTED_MESSAGE = os.environ.get(
    'LOOKUP_REGION_RESTRICTED_MESSAGE',
    'PeopleGraph is currently available only to users in Pakistan. We appreciate your interest and hope to serve your region in the future.',
)
IPINFO_API_TOKEN = os.environ.get('IPINFO_API_TOKEN', '').strip()
IPINFO_LITE_URL = os.environ.get('IPINFO_LITE_URL', 'https://api.ipinfo.io/lite').rstrip('/')
IPINFO_TIMEOUT_SECONDS = env_int('IPINFO_TIMEOUT_SECONDS', 8, minimum=2, maximum=30)
IPINFO_ALLOWED_CACHE_DAYS = env_int('IPINFO_ALLOWED_CACHE_DAYS', 30, minimum=1, maximum=365)
IPINFO_DENIED_CACHE_HOURS = env_int('IPINFO_DENIED_CACHE_HOURS', 24, minimum=1, maximum=168)

CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE', '1048576'))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE', '1048576'))

SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', not DEBUG)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = env_bool('DJANGO_CSRF_COOKIE_HTTPONLY', True)
SESSION_COOKIE_SAMESITE = os.environ.get('DJANGO_SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = os.environ.get('DJANGO_CSRF_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_AGE = int(os.environ.get('DJANGO_SESSION_COOKIE_AGE', '43200'))
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0' if DEBUG else '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', not DEBUG)
SECURE_HSTS_PRELOAD = env_bool('DJANGO_SECURE_HSTS_PRELOAD', False)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
REFERRER_POLICY = os.environ.get('DJANGO_REFERRER_POLICY', 'strict-origin-when-cross-origin')

if env_bool('DJANGO_TRUST_PROXY_HEADERS', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

TRUST_X_FORWARDED_FOR = env_bool('DJANGO_TRUST_X_FORWARDED_FOR', False)

ADMIN_URL_PATH = os.environ.get('DJANGO_ADMIN_URL_PATH', 'admin/').strip() or 'admin/'
if not ADMIN_URL_PATH.endswith('/'):
    ADMIN_URL_PATH = f'{ADMIN_URL_PATH}/'

if not DEBUG and not CORS_ALLOWED_ORIGINS:
    raise ImproperlyConfigured('DJANGO_CORS_ALLOWED_ORIGINS must be set in production.')

if not DEBUG and any(origin.startswith('http://') for origin in CORS_ALLOWED_ORIGINS):
    raise ImproperlyConfigured('Production CORS origins must use HTTPS.')

if not DEBUG and not LOOKUP_ALLOWED_ORIGINS:
    raise ImproperlyConfigured('LOOKUP_ALLOWED_ORIGINS must be set in production.')

LOOKUP_THROTTLE_RATE = os.environ.get('LOOKUP_THROTTLE_RATE', '30/min')
ADMIN_LOGIN_FAILURE_LIMIT = env_int('ADMIN_LOGIN_FAILURE_LIMIT', 8, minimum=3, maximum=50)
ADMIN_LOGIN_FAILURE_WINDOW_SECONDS = env_int(
    'ADMIN_LOGIN_FAILURE_WINDOW_SECONDS',
    900,
    minimum=60,
    maximum=86400,
)
SECONDARY_RELAY_MAX_RESPONSE_BYTES = env_int(
    'SECONDARY_RELAY_MAX_RESPONSE_BYTES',
    2097152,
    minimum=1024,
    maximum=10485760,
)

CORS_ALLOWED_ORIGINS = CORS_ALLOWED_ORIGINS

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'lookups.throttles.PublicIPScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'lookup': LOOKUP_THROTTLE_RATE,
    },
}
